site_name: AVWX Engine
site_url: https://engine.avwx.rest
site_description: AVWX Engine Package Documentation
site_author: Michael duPont
repo_url: https://github.com/avwx-rest/avwx-engine

theme:
  name: material
  logo: assets/images/avwx-icon-32-white.png
  favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.snippets:
    check_paths: true
  - pymdownx.superfences

extra:
  homepage: https://avwx.rest

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Getting Started: getting-started.md
  - Aviation:
    - METAR: av/metar.md
    - TAF: av/taf.md
    - PIREP: av/pirep.md
    - AIRMET / SIGMET: av/airsigmet.md
    - NOTAM: av/notam.md
  - Models:
    - NBM NBH: nbm/nbh.md
    - NBM NBS: nbm/nbs.md
    - NBM NBE: nbm/nbe.md
    - GFS MOS MAV: gfs/mav.md
    - GFS MOS MEX: gfs/mex.md
  - Utilities:
    - Station: util/station.md
    - Data Services: util/service.md
    - Data Updates: util/data.md
    - Data Structures: util/structs.md
    - Static Values: util/static.md
    - Exceptions: util/exceptions.md

copyright: Copyright &copy; 2022 duPont Technologies LLC

plugins:
  - search
  - minify:
    minify_html: true
    htmlmin_opts:
      remove_comments: true
  - mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_signature_annotations: true
          show_source: true
    watch:
      - avwx-engine
