version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.8

jobs:
  test-3.8: &test-template
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install nox
          command: sudo pip install nox
      - run:
          name: Run Nox
          command: nox

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
