version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-3.8
      - test-3.9
      - test-3.10

jobs:
  test-3.10: &test-template
    docker:
      - image: circleci/python:3.10

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install nox
          command: sudo pip install nox
      - run:
          name: Run Nox
          command: nox

  test-3.9:
    <<: *test-template
    docker:
      - image: circleci/python:3.9

  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8
