name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  # Build code and docs then deploy to PyPI
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
      - name: Publish to pypi
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build --no-interaction
      - name: Build docs
        run: |
          poetry run python -m pdoc ./avwx -o docs_b/ \
          --favicon https://raw.githubusercontent.com/avwx-rest/avwx-engine/main/docs/assets/images/favicon.ico \
          --logo https://raw.githubusercontent.com/avwx-rest/avwx-engine/main/docs/assets/images/avwx-logo-color-200.png \
          --logo-link https://info.avwx.rest
          echo "engine.avwx.rest" > docs_b/CNAME
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs_b/

  # Deploy the doc build to GitHub pages
  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2